name: "Send Discord alerts"
description: "Builds the project's docker image, pushes to container repo, and deploys on the server"
runs:
  using: composite
  steps:
    - uses: technote-space/workflow-conclusion-action@v2

    - name: Alert on success
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_EMBEDS: '[
          {
            "title": "**Job succeeded!**",
            "description": "[**${{ github.repository }}**](${{ github.server_url }}/${{ github.repository }})",
            "color": 4714567,
            "fields": [
              {
                "name": "Job",
                "value": "**[${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**",
                "inline": true
              },
              {
                "name": "Triggered by",
                "value": "[${{ github.actor }}](${{ github.server_url }}/${{ github.actor }})",
                "inline": true
              }
            ],
            "author": {
              "name": "GitHub Actions",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions",
              "icon_url": "https://i.imgur.com/z0f8jOI.jpg"
            },
            "footer": {
              "text": "Status: ${{ env.WORKFLOW_CONCLUSION }}",
              "icon_url": "https://i.imgur.com/CzJAQiV.png"
            }
          }
        ]'
      if: env.WORKFLOW_CONCLUSION == 'success'

    - name: Alert on failure
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_EMBEDS: '[
          {
            "title": "**Job failed!**",
            "description": "[**${{ github.repository }}**](${{ github.server_url }}/${{ github.repository }})",
            "color": 15746887,
            "fields": [
              {
                "name": "Job",
                "value": "**[${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**",
                "inline": true
              },
              {
                "name": "Triggered by",
                "value": "[${{ github.actor }}](${{ github.server_url }}/${{ github.actor }})",
                "inline": true
              }
            ],
            "author": {
              "name": "GitHub Actions",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions",
              "icon_url": "https://i.imgur.com/z0f8jOI.jpg"
            },
            "footer": {
              "text": "Status: ${{ env.WORKFLOW_CONCLUSION }}",
              "icon_url": "https://i.imgur.com/O0I9Mmr.png"
            }
          }
        ]'
      if: env.WORKFLOW_CONCLUSION == 'failure' || env.WORKFLOW_CONCLUSION == 'timed_out'
